os:
- linux
language: node_js
node_js:
- lts/carbon
- lts/dubnium
- stable
cache:
  directories:
  - node_modules
after_success:
- yarn run build
- yarn run sonarconfig
- sonar-scanner
deploy:
  provider: npm
  email: robert.kleger@bobb.io
  skip_cleanup: true
  on:
    tags: true
    branch: master
  api_key: $NPM_TOKEN
addons:
  sonarcloud:
    organization: danautilus-github
    token:
      secure: $SONAR_TOKEN
